# Generated by Django 5.1 on 2024-09-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_ict0jq.jpg', upload_to='samples/'),
        ),
    ]
