# Generated by Django 5.1 on 2024-09-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dloir5ckh/image/upload/v1722351140/samples/default_profile_ict0jq.jpg', upload_to='images/'),
        ),
    ]
